<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Laporan Pembelian</title>
</head>

<body>
    {{-- <div style="margin-bottom:25px;"><strong>Report generated by: {{ $param }}</strong></div> --}}
    <table style="border-collapse: collapse;">
        <thead>
            <tr>
                <th style="border-bottom:2pt solid black;">
                    <strong>Tanggal</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Kode Transaksi</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Nama Supplier</strong>
                </th>
                <th style="border-bottom:2pt solid black;">
                    <strong>Total Bayar</strong>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach ($purchases as $purchase)
                <tr>
                    <td style="border-bottom:1pt solid black;">
                        {{ $purchase->date }}
                    </td>
                    <td style="border-bottom:1pt solid black;">
                        {{ $purchase->code }}
                    </td>
                    <td style="border-bottom:1pt solid black;">
                        {{ $purchase->supplier_name }}
                    </td>
                    <td style="border-bottom:1pt solid black;">
                        {{ $purchase->total_price }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>

</html>
